# Inserts a blank line between shell prompts
add_newline = true

format='''
[â•­â”€â”€](bold red)in$directory
[â•°â”€â”€](bold red)$cmd_duration$character
'''

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[battery]
disabled = true

[character]
success_symbol = "ğŸ§ğŸ’™ [â¯](bold red)"
error_symbol = "á¶ á¶¸á¶œáµáµ§â‚’áµ¤ï¼[â¯](bold green)"
